name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']
    types: [opened, reopened, synchronize, edited, ready_for_review]

jobs:
    unit-tests:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                node-version: "18"
            - name: Install dependencies
              run: npm install    
            - name: Run tests
              run: npm test